spring:
  thymeleaf:
    cache: false
  messages:
    basename: i18n.login
  application:
    name: springboot-https
  datasource:
    url: jdbc:mysql://localhost:3306/cfphonesubmitinfo?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
#    url: jdbc:mysql://localhost:3306/cfphonesubmitinfo?useUnicode=true&characterEncoding=utf-8
    username: root
    password: '08290516'
    type: com.alibaba.druid.pool.DruidDataSource

    #Spring Boot 默认是不注入这些属性值的，需要自己绑定
    #druid 数据源专有配置


    #配置监控统计拦截的filters，stat:监控统计、log4j：日志记录、wall：防御sql注入
    #如果允许时报错  java.lang.ClassNotFoundException: org.apache.log4j.Priority
    #则导入 log4j 依赖即可，Maven 地址：https://mvnrepository.com/artifact/log4j/log4j
#    filters: stat,wall,log4j
#    maxPoolPreparedStatementPerConnectionSize: 20
#    useGlobalDataSourceStat: true
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8081
#  port: 443
#  ssl:
#    key-store: classpath:4257729_www.cfphone.top.pfx
#    key-store-password: 59b8ntzr
#    keyStoreType: PKCS12

